### ISSUE TITLE
python player and cache

### ISSUE THREAD

**Issue by ctotof38** [deezer/native-sdk-samples#18]
Hello,
I notice that the player use a cache directory. In it, we can find the data of each listen music. I suppose this cache is used when we want to read a previous file, we use the cache.

But this cache increase in size all the time. On my Raspberry Pi, I do some measure. The cache was in /tmp, which is a tmpfs mount point.

At the begining:
```
df -k /tmp
Filesystem           1K-blocks      Used Available Use% Mounted on
tmpfs                   473976      3924    470052   1% /tmp

```

After 20 musics
```
df -k /tmp
Filesystem           1K-blocks      Used Available Use% Mounted on
tmpfs                   473976     61756    412220  13% /tmp

```

And after 209 musics
```
df -k /tmp
Filesystem           1K-blocks      Used Available Use% Mounted on
tmpfs                   473976      473976       0 100% /tmp

```

In this case, the player stop playing music, but it still running. I have the error:
```
98855:382995 dz_bufferevent: [dz_bufferevent_on_file_write:294] write event ENOSPC write_wanted_len:4096 write_done_len:4294967268
98855:383460 block_trackfile_writer: [mediafile_writer_receive_data_eventcb:230] event:3 0x7299fc78

```

I stopped it and started it a new time, the cache is not deleted. So, I have the error message 

`99297:524846 resourcecache: [dz_resourcecache_db_load:1045] assert failed: wal_checkpoint rc=13 database or disk is full`

It would be interesting to have a behavior which limit the size of its cache. When a threshold is met, we purge older files. What do you think of this features ?

Currently, I can decide to delete some big file in the cache but I don't know if it is a good solution. Currently, I delete the cache each time I start the player.

Regards

Christophe

**Comment by CPicheney** [comment]
Hello Christophe,

Thank you for your feedback.

It is a good question that need clarification.

There is a cache size limitation function that can be called: `dz_connect_smartcache_quota_set` otherwise the cache is unlimited...I think I have to improve this with a default cache size.

This can be coupled with a setting of a different cache path by calling this function:
`dz_connect_cache_path_set` (there is an example in NanoPlayer)

I hope it will help.

Best regards,

Cyril
